Repository etclabscore/ECIPs, pull requests merged in 2019-03, with the labels that each got.

#3 Feature/openrpc
  ECLIPs/ECLIP-3.md
Labels: enhancement

#9 Remove the L in ECLIPs
  ECIP-1.sample.md
  ECIP-number.template.md
  ECIP-template.md
  ECIPs/.gitignore
  ECIPs/ECIP-1000.mediawiki
  ECIPs/ECIP-1010.md
  ECIPs/ECIP-1013.md
  ECIPs/ECIP-1015.md
  ECIPs/ECIP-1016.md
  ECIPs/ECIP-1017.md
  ECIPs/ECIP-1017_cn.md
  ECIPs/ECIP-1018.md
  ECIPs/ECIP-1019.md
  ECIPs/ECIP-1021.md
  ECIPs/ECIP-1025.md
  ECIPs/ECIP-1026.md
  ECIPs/ECIP-1027.md
  ECIPs/ECIP-1028.md
  ECIPs/ECIP-1035.md
  ECIPs/ECIP-1036.md
  ECIPs/ECIP-1037.md
  ECIPs/ECIP-1039.md
  ECIPs/ECIP-1041.md
  ECIPs/ECIP-1042.md
  ECIPs/ECIP-1043.md
  ECIPs/ECIP-1044.md
  ECIPs/ECIP-1045.md
  ECIPs/ECIP-1046.md
  ECIPs/ECIP-1047.md
  ECIPs/ECIP-1048.md
  ECIPs/ECIP-1049.md
  ECIPs/ECIP-1050.md
  ECIPs/ECIP-1051.md
  ECIPs/ECIP-1052.md
  ECIPs/ECIP-1053.md
  ECIPs/ETC_MP_5M20.png
  ECIPs/ETC_MP_Perpetual.png
  ECLIPs/ECIP-1030.md
  ECLIPs/ECLIP-1.md
  ECLIPs/ECLIP-3.md
  README.md
  process.png
Labels: review wanted

#10 ECIP-1054: Support for ETH Byzantium EVM and Protocol Upgrades
  ECLIPs/ECIP-1054.md
Labels: consensus, review wanted
